### ISSUE TITLE
Updating issue

### ISSUE THREAD

**Issue by oomocks** [pyppeteer/pyppeteer#103]
When I update Pyppeteer to version 0.2.2 the pip list shows this has happened, but when I run the following on the command line REPL

import pyppeteer
print (pyppeteer._version_)

it shows as the old version 0.0.25. Has anyone encountered this issue before? I'm running it on Raspian on a Pi4 and using Python 3.7.

Many thanks in advance for any help.

**Comment by Mattwmaster58** [comment]
Looks like that was an oversight on our part and it should be fixed in the next release. The package defines the version `0.2.2`, however, the \_\_version\_\_ attribute is erroneously specified as 0.0.25. 

It's such a small issue that I don't think it warrants an update, but if you feel otherwise I'm open to discussion.

Hope this helps.

**Comment by oomocks** [comment]
Many thanks for letting me know, Matt. Good to know it wasn't that I had done something wrong.
