### ISSUE TITLE
page.evaluate use js code no work

### ISSUE THREAD

**Issue by colinsarah** [pyppeteer/pyppeteer#331]
**JS replace func couldn't work**
inner html is
> "\u003cdd\u003e：bnabu@gmail.com\u003c/dd\u003e\n"
```python
page.evaluate(
"""
var html_content=unescape(document.body.innerHTML.replace(/\\u/gi,'%u'));
 console.log("content:",html_content)
"""
)
```
console is 
>"\u003cdd\u003e：bnab%u@gmail.com\u003c/dd\u003e\n"

**u is replace %u not \u**  just confused me，Thanks for any help

**Comment by haakenlid** [comment]
This doesn't look like an issue with pyppeteer. Clearly the javascript code is executed with no error, but you don't get the output you want. The problem seems to be in your javascript code, not pyppeteer.

`\u` is used for unicode escape sequences, and using regex in this way might not work as you expect. You could try asking this question on stackoverflow instead. Just remember to explain what your expected output is.

**Comment by colinsarah** [comment]
Thanks
